---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- name: "remove dependencies that are no longer required"
  become: yes
  apt:
    autoremove: yes


- name: "install make"
  become: yes
  shell: |
           sudo apt install make -y
           #make --version
  args:
     warn: false

- name: "install hadolint"
  become: yes
  shell: |
          sudo wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v2.7.0/hadolint-Linux-x86_64 && sudo chmod +x /bin/hadolint
          #hadolint --version
  args:
     warn: false
- name: "Setup the Environment"
  become: yes
  shell: |
           sudo apt-get install python3-venv -y
           python3 -m venv ~/.devops
           source ~/.devops/bin/activate
  args:
     warn: false





